server:
  port: 8010 # 서버 포트(기본값은 8080)
spring:
  thymeleaf:
    cache: false # 타임리프 캐시 끄기
    prefix: file:src/main/resources/templates/ # 타임리프 캐시 끄기(이 설정을 해야 꺼짐)
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/basic1__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 1226
  jpa:
    hibernate:
      #show-auto: create # DB 테이블 자동생성(엔티티 클래스만 만들면 됨)
      show_sql: true
      format_sql: true #sql 쿼리들이 좀 더 깔끔하게
      use_sql_comments: true #JPQL

